FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io awscli curl unzip git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Give jenkins user docker access
RUN usermod -aG docker jenkins

USER jenkins
